### ISSUE TITLE
The code is missing DiViDeAddEvaluator

### ISSUE THREAD

**Issue by qinqinqaq** [QMME/StableVQA#3]

**Comment by QMME** [comment]
There is an error. In stable.yml, it should be Stablev2Evaluator. It has now been corrected.

**Comment by qinqinqaq** [comment]
> There is an error. In stable.yml, it should be Stablev2Evaluator. It has now been corrected.

Thank you for your reply. I will try！

**Comment by qinqinqaq** [comment]
> There is an error. In stable.yml, it should be Stablev2Evaluator. It has now been corrected.

May I ask this stable.yml is just the execution command of FAST-VQA? Is there a Stable-VQA execution code?

**Comment by QMME** [comment]
Should be ok by now.
